// Mocks generated by Mockito 5.4.4 from annotations
// in sirenapp_flutter_inbox/test/data/siren_data_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sirenapp_flutter_inbox/src/api/verify_token.dart' as _i4;
import 'package:sirenapp_flutter_inbox/src/constants/generics.dart' as _i5;
import 'package:sirenapp_flutter_inbox/src/models/api_response.dart' as _i3;
import 'package:sirenapp_flutter_inbox/src/services/api_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_1 extends _i1.SmartFake implements _i3.ApiResponse {
  _FakeApiResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VerifyToken].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyToken extends _i1.Mock implements _i4.VerifyToken {
  @override
  _i2.ApiClient get api => (super.noSuchMethod(
        Invocation.getter(#api),
        returnValue: _FakeApiClient_0(
          this,
          Invocation.getter(#api),
        ),
        returnValueForMissingStub: _FakeApiClient_0(
          this,
          Invocation.getter(#api),
        ),
      ) as _i2.ApiClient);

  @override
  set api(_i2.ApiClient? _api) => super.noSuchMethod(
        Invocation.setter(
          #api,
          _api,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Status convertJsonToVerificationStatus(dynamic response) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertJsonToVerificationStatus,
          [response],
        ),
        returnValue: _i5.Status.PENDING,
        returnValueForMissingStub: _i5.Status.PENDING,
      ) as _i5.Status);

  @override
  _i6.Future<_i3.ApiResponse> verifyToken() => (super.noSuchMethod(
        Invocation.method(
          #verifyToken,
          [],
        ),
        returnValue: _i6.Future<_i3.ApiResponse>.value(_FakeApiResponse_1(
          this,
          Invocation.method(
            #verifyToken,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.ApiResponse>.value(_FakeApiResponse_1(
          this,
          Invocation.method(
            #verifyToken,
            [],
          ),
        )),
      ) as _i6.Future<_i3.ApiResponse>);
}
