// Mocks generated by Mockito 5.4.4 from annotations
// in sirenapp_flutter_inbox/test/widgets/siren_inbox_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sirenapp_flutter_inbox/sirenapp_flutter_inbox.dart' as _i3;
import 'package:sirenapp_flutter_inbox/src/api/fetch_unviewed_notification_count.dart'
    as _i8;
import 'package:sirenapp_flutter_inbox/src/constants/generics.dart' as _i7;
import 'package:sirenapp_flutter_inbox/src/data/siren_data_provider.dart'
    as _i5;
import 'package:sirenapp_flutter_inbox/src/services/api_client.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStreamController_0<T> extends _i1.SmartFake
    implements _i2.StreamController<T> {
  _FakeStreamController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSirenErrorType_1 extends _i1.SmartFake
    implements _i3.SirenErrorType {
  _FakeSirenErrorType_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiClient_2 extends _i1.SmartFake implements _i4.ApiClient {
  _FakeApiClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_3 extends _i1.SmartFake implements _i3.ApiResponse {
  _FakeApiResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SirenDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSirenDataProvider extends _i1.Mock implements _i5.SirenDataProvider {
  @override
  String get userToken => (super.noSuchMethod(
        Invocation.getter(#userToken),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userToken),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userToken),
        ),
      ) as String);

  @override
  set userToken(String? _userToken) => super.noSuchMethod(
        Invocation.setter(
          #userToken,
          _userToken,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get recipientId => (super.noSuchMethod(
        Invocation.getter(#recipientId),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#recipientId),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#recipientId),
        ),
      ) as String);

  @override
  set recipientId(String? _recipientId) => super.noSuchMethod(
        Invocation.setter(
          #recipientId,
          _recipientId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get apiDomain => (super.noSuchMethod(
        Invocation.getter(#apiDomain),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#apiDomain),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#apiDomain),
        ),
      ) as String);

  @override
  set apiDomain(String? _apiDomain) => super.noSuchMethod(
        Invocation.setter(
          #apiDomain,
          _apiDomain,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.StreamController<_i3.StreamResponse> get inboxController =>
      (super.noSuchMethod(
        Invocation.getter(#inboxController),
        returnValue: _FakeStreamController_0<_i3.StreamResponse>(
          this,
          Invocation.getter(#inboxController),
        ),
        returnValueForMissingStub: _FakeStreamController_0<_i3.StreamResponse>(
          this,
          Invocation.getter(#inboxController),
        ),
      ) as _i2.StreamController<_i3.StreamResponse>);

  @override
  _i2.StreamController<_i3.StreamResponse> get iconController =>
      (super.noSuchMethod(
        Invocation.getter(#iconController),
        returnValue: _FakeStreamController_0<_i3.StreamResponse>(
          this,
          Invocation.getter(#iconController),
        ),
        returnValueForMissingStub: _FakeStreamController_0<_i3.StreamResponse>(
          this,
          Invocation.getter(#iconController),
        ),
      ) as _i2.StreamController<_i3.StreamResponse>);

  @override
  _i7.Status get tokenVerificationStatus => (super.noSuchMethod(
        Invocation.getter(#tokenVerificationStatus),
        returnValue: _i7.Status.PENDING,
        returnValueForMissingStub: _i7.Status.PENDING,
      ) as _i7.Status);

  @override
  bool get isProviderInitialized => (super.noSuchMethod(
        Invocation.getter(#isProviderInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  void updateParams({
    required String? userToken,
    required String? recipientId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateParams,
          [],
          {
            #userToken: userToken,
            #recipientId: recipientId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void triggerEvent(_i7.UpdateEvents? event) => super.noSuchMethod(
        Invocation.method(
          #triggerEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.SirenErrorType getVerificationErrorType() => (super.noSuchMethod(
        Invocation.method(
          #getVerificationErrorType,
          [],
        ),
        returnValue: _FakeSirenErrorType_1(
          this,
          Invocation.method(
            #getVerificationErrorType,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSirenErrorType_1(
          this,
          Invocation.method(
            #getVerificationErrorType,
            [],
          ),
        ),
      ) as _i3.SirenErrorType);

  @override
  void iconDispose() => super.noSuchMethod(
        Invocation.method(
          #iconDispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void inboxDispose() => super.noSuchMethod(
        Invocation.method(
          #inboxDispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FetchUnViewedNotificationsCount].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchUnViewedNotificationsCount extends _i1.Mock
    implements _i8.FetchUnViewedNotificationsCount {
  @override
  _i4.ApiClient get api => (super.noSuchMethod(
        Invocation.getter(#api),
        returnValue: _FakeApiClient_2(
          this,
          Invocation.getter(#api),
        ),
        returnValueForMissingStub: _FakeApiClient_2(
          this,
          Invocation.getter(#api),
        ),
      ) as _i4.ApiClient);

  @override
  set api(_i4.ApiClient? _api) => super.noSuchMethod(
        Invocation.setter(
          #api,
          _api,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Future<_i3.ApiResponse> fetchUnViewedNotificationsCount() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUnViewedNotificationsCount,
          [],
        ),
        returnValue: _i2.Future<_i3.ApiResponse>.value(_FakeApiResponse_3(
          this,
          Invocation.method(
            #fetchUnViewedNotificationsCount,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i2.Future<_i3.ApiResponse>.value(_FakeApiResponse_3(
          this,
          Invocation.method(
            #fetchUnViewedNotificationsCount,
            [],
          ),
        )),
      ) as _i2.Future<_i3.ApiResponse>);
}
